### ISSUE TITLE
System.ArgumentNullException: Value cannot be null in Windows Phone 8 store app.

### ISSUE THREAD

**Issue by yenelcs** [MehdiK/Humanizer#372] opened 2015-01-09 19:21 UTC
Hi,

I am using Humanizer in one of my projects to humanizer TimeSpan and I see this error at a rate of 1000 instances per day. Can you please take a look?

Thanks.

System.ArgumentNullException: Value cannot be null.
Parameter name: format
   at System.String.Format(String format, Object[] args)
   at Humanizer.Localisation.Formatters.DefaultFormatter.Format(String resourceKey, Int32 number)
   at Humanizer.Localisation.Formatters.DefaultFormatter.GetResourceForTimeSpan(TimeUnit unit, Int32 count)
   at Humanizer.Localisation.Formatters.DefaultFormatter.TimeSpanHumanize(TimeUnit timeUnit, Int32 unit)
   at Humanizer.TimeSpanHumanizeExtensions.GetTimePart(TimeSpan timespan, CultureInfo culture)
   at Humanizer.TimeSpanHumanizeExtensions.Humanize(TimeSpan timeSpan, Int32 precision, CultureInfo culture)
   at Flashlight.MainPage.SetBatteryText(Int32 remainingChargePercent, TimeSpan remainingDischargeTime)

**Comment by MehdiK** [comment] 2015-01-20 21:52
Thanks for reporting @yenelcs 

This is the first time I see this error and it's quite strange. What locale are you using and what are the TimeUnit and the count that cause this error? Would you please be able to send us a repro file/project?

**Comment by yenelcs** [comment] 2015-01-20 22:11
@MehdiK Unfortunately I don't have a repro project. It happens on production. All I try to do is Humanize a timespan structure with count = 2. Some locale that this error happening are: Romanian (Romania), Czech (Czech Republic), Romanian (Romania), English (United Kingdom), Serbian (Latin, Serbia), Slovak (Slovakia), English (United States), Romanian (Romania). Top 3 locale are Serbian (Latin, Serbia), Romanian (Romania) and Slovak (Slovakia).

Thanks,

**Comment by yenelcs** [comment] 2015-01-21 01:00
@MehdiK TimeSpanHumanize_MultipleMilliseconds is missing in the resources. Could it be the reason?

**Comment by MehdiK** [comment] 2015-01-21 08:09
Hmmm, that's interesting and most likely the cause of the problem. Which resources file was missing the entries?

**Comment by yenelcs** [comment] 2015-01-21 19:57
Default one = English.

**Comment by MehdiK** [comment] 2015-01-23 03:47
Would you please be able to update to the latest and see if the problem persists?

**Comment by yenelcs** [comment] 2015-01-25 19:44
I updated the Humanizer from nuget to version 1.32. This issue still happens but number of exceptions per day dropped ~%90 which is good. However there might be some entries in the code that are being used but not present in the resources.

**Comment by MehdiK** [comment] 2015-01-25 23:53
Thanks for the update. It's a shame some of the resources are missing. Would you be able to dig further to see what resources might be missing so we can add them back in please? Thanks.

**Comment by yenelcs** [comment] 2015-01-27 22:12
Ok, I will try.

**Comment by MehdiK** [comment] 2015-01-30 00:08
Awesome. Thanks a lot. Would you be able to send a PR with missing keys please?

It would also be very beneficial to have a unit test that verifies the keys to avoid missing keys in the future.

**Comment by CurrentThread** [comment] 2015-07-23 19:57
First commit to GitHub, I think that I made a mistake… Can someone please help me to fix? Sorry.

**Comment by MehdiK** [comment] 2015-08-17 11:09
This should hopefully be fixed by #446. Will release soon.

**Closed by MehdiK** 2015-08-17 11:09 UTC
Labels: bug, jump in, localisation
